//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDL.Trados.MTUOC {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PluginResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PluginResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SDL.Trados.MTUOC.PluginResources", typeof(PluginResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Advanced.
        /// </summary>
        public static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cache.
        /// </summary>
        public static string Cache {
            get {
                return ResourceManager.GetString("Cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Connection test.
        /// </summary>
        public static string CheckConnection {
            get {
                return ResourceManager.GetString("CheckConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to clear cache?.
        /// </summary>
        public static string ConfirmRemoveCache {
            get {
                return ResourceManager.GetString("ConfirmRemoveCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to delete the selected items?.
        /// </summary>
        public static string ConfirmRemoveTranslations {
            get {
                return ResourceManager.GetString("ConfirmRemoveTranslations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] countries {
            get {
                object obj = ResourceManager.GetObject("countries", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete cache.
        /// </summary>
        public static string DeleteCache {
            get {
                return ResourceManager.GetString("DeleteCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Description:.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The same translation language cannot be entered in source and destination.
        /// </summary>
        public static string ErrorDuplicateLanguage {
            get {
                return ResourceManager.GetString("ErrorDuplicateLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A record with the same translation already exists.
        /// </summary>
        public static string ErrorTranslationDuplicate {
            get {
                return ResourceManager.GetString("ErrorTranslationDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must select at least one translation.
        /// </summary>
        public static string ErrorTranslationsEmpty {
            get {
                return ResourceManager.GetString("ErrorTranslationsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Information.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Languaje selection.
        /// </summary>
        public static string LanguajeSelection {
            get {
                return ResourceManager.GetString("LanguajeSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        /// </summary>
        public static System.Drawing.Icon LogoMTUOC {
            get {
                object obj = ResourceManager.GetObject("LogoMTUOC", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        /// </summary>
        public static System.Drawing.Icon LogoUOC {
            get {
                object obj = ResourceManager.GetObject("LogoUOC", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Text:.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MTUOC - MACHINE TRANSLATION.
        /// </summary>
        public static string Plugin_Name {
            get {
                return ResourceManager.GetString("Plugin_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;PluginPackage xmlns=&quot;http://www.sdl.com/Plugins/PluginPackage/1.0&quot;&gt;
        ///  &lt;PlugInName&gt;SDL.Trados.MTUOC&lt;/PlugInName&gt;
        ///  &lt;Version&gt;1.0.8&lt;/Version&gt;
        ///  &lt;Description&gt;Plugin description&lt;/Description&gt;
        ///  &lt;Author&gt;&lt;/Author&gt;
        ///  &lt;Include&gt;
        ///    &lt;File&gt;Polly.dll&lt;/File&gt;
        ///    &lt;File&gt;Microsoft.Extensions.DependencyInjection.Abstractions.dll&lt;/File&gt;
        ///    &lt;File&gt;Microsoft.Extensions.DependencyInjection.dll&lt;/File&gt;
        ///    &lt;File&gt;Microsoft.Extensions.Http.dll&lt;/File&gt;
        ///    &lt;File&gt;Microsoft.Bcl.AsyncIn [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string pluginpackage_manifest {
            get {
                return ResourceManager.GetString("pluginpackage_manifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Port:.
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MTUOC - MACHINE TRANSLATION.
        /// </summary>
        public static string ProviderFactoryInfo {
            get {
                return ResourceManager.GetString("ProviderFactoryInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pwd.
        /// </summary>
        public static string Pwd {
            get {
                return ResourceManager.GetString("Pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Translation:.
        /// </summary>
        public static string Response {
            get {
                return ResourceManager.GetString("Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Score:.
        /// </summary>
        public static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Segment already translated.
        /// </summary>
        public static string SegmentAlreadyTranslated {
            get {
                return ResourceManager.GetString("SegmentAlreadyTranslated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IP:.
        /// </summary>
        public static string ServerIp {
            get {
                return ResourceManager.GetString("ServerIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show Password.
        /// </summary>
        public static string ShowPassword {
            get {
                return ResourceManager.GetString("ShowPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Source.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Target.
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Message received successfully.
        /// </summary>
        public static string TestConnectionOk {
            get {
                return ResourceManager.GetString("TestConnectionOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This is a test message!.
        /// </summary>
        public static string TestMessage {
            get {
                return ResourceManager.GetString("TestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cache expiration time in seconds.
        /// </summary>
        public static string TimeExpiredCache {
            get {
                return ResourceManager.GetString("TimeExpiredCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Keep the caché (days):.
        /// </summary>
        public static string TimeExpiredCacheFile {
            get {
                return ResourceManager.GetString("TimeExpiredCacheFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Translation configuration.
        /// </summary>
        public static string TranslateConfig {
            get {
                return ResourceManager.GetString("TranslateConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MTUOC translation provider.
        /// </summary>
        public static string TranslationProviderName {
            get {
                return ResourceManager.GetString("TranslationProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MTUOC.
        /// </summary>
        public static string TranslationProviderStatusInfo {
            get {
                return ResourceManager.GetString("TranslationProviderStatusInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Server configuration:.
        /// </summary>
        public static string WelcomeToMTUOC {
            get {
                return ResourceManager.GetString("WelcomeToMTUOC", resourceCulture);
            }
        }
    }
}
